-- 20260503000000_add_field_level_relations.sql
-- Phase 1a prereq per docs/plans/20260501-universal-wysiwyg-schema-ux-v1.00W.md §2.6.
-- Adds field-level FK columns to tenant_entity_relations + confirms Realtime.
--
-- ⚠️  DEV-FIXTURE COPY — DO NOT EDIT HERE.
-- Canonical location: business-suite-unified/supabase/migrations/20260503000000_add_field_level_relations.sql
-- This copy exists only so `pnpm --filter @bsuite/schema-builder test` can spin
-- up a self-contained Supabase fixture. See README.md in this directory for the
-- hard rule and sync workflow.

-- @sync-boundary-below
-- Everything below this line MUST be byte-identical with the BSU canonical copy.
-- CI parity check (.github/workflows/schema-builder-migration-parity.yml) enforces it.


-- 1. Field-level FK columns (nullable — entity-to-entity rows stay valid)
--    FK constraints are managed explicitly in a DO block below to guarantee
--    ON DELETE CASCADE semantics (see §2).
ALTER TABLE public.tenant_entity_relations
  ADD COLUMN IF NOT EXISTS source_field_id uuid,
  ADD COLUMN IF NOT EXISTS target_field_id uuid;

COMMENT ON COLUMN public.tenant_entity_relations.source_field_id IS
  'Field-level FK source column. NULL = entity-to-entity relation (legacy). '
  'Set by Schema Builder when the user drags from a field-row handle per §3.9. '
  'FK has ON DELETE CASCADE — deleting a field drops its relations (see §2).';

COMMENT ON COLUMN public.tenant_entity_relations.target_field_id IS
  'Field-level FK target column. Almost always the primary key of the target entity. '
  'FK has ON DELETE CASCADE — deleting a field drops its relations (see §2).';

-- 1b. Referential-action columns for field-level FKs
ALTER TABLE public.tenant_entity_relations
  ADD COLUMN IF NOT EXISTS on_delete text
    CHECK (on_delete IS NULL OR on_delete IN ('CASCADE', 'SET NULL', 'RESTRICT', 'NO ACTION')),
  ADD COLUMN IF NOT EXISTS on_update text
    CHECK (on_update IS NULL OR on_update IN ('CASCADE', 'SET NULL', 'RESTRICT', 'NO ACTION'));

COMMENT ON COLUMN public.tenant_entity_relations.on_delete IS
  'ON DELETE referential action for field-level FKs. NULL for entity-level rows. '
  'Note: the underlying FK on source_field_id / target_field_id is always CASCADE at '
  'the database level (so the relation row is dropped when either field is deleted); '
  'this column records the user-facing intent for the emitted Postgres FK on the data '
  'column itself (via apply_schema_relation RPC).';
COMMENT ON COLUMN public.tenant_entity_relations.on_update IS
  'ON UPDATE referential action for field-level FKs. NULL for entity-level rows.';

-- 2. Foreign-key constraints with ON DELETE CASCADE semantics.
--
-- CRITICAL DESIGN NOTE — do not change to SET NULL without re-reviewing §3.
-- The chk_field_level_pair CHECK constraint below requires source_field_id and
-- target_field_id to be both NULL or both NOT NULL. If the FKs used ON DELETE
-- SET NULL, deleting a referenced field would set only ONE column to NULL,
-- violating the CHECK and aborting the DELETE with a confusing error. CASCADE
-- is the correct choice: when either field is deleted, the whole relation row
-- disappears, which is what users expect ("delete a field → relations gone").
--
-- 2a. Repair block — drops any pre-existing non-CASCADE FK on
--     source_field_id / target_field_id from an earlier draft migration.
--     Idempotent: no-op if all such FKs are already CASCADE.
--
--     Belt-and-braces match using two strategies (OR'd) so the repair is
--     robust against naming variance:
--
--       (a) Column-based (primary, most robust) — matches any FK whose
--           constrained column is source_field_id or target_field_id,
--           regardless of constraint name. Catches manually-created FKs
--           with custom names.
--
--       (b) Name-based (fallback) — matches the Postgres default
--           `<table>_<col>_fkey` names generated by inline REFERENCES on
--           ADD COLUMN in the original Draft-1 migration. Kept as a
--           belt-and-braces layer in case pg_attribute is somehow absent
--           from the join (shouldn't happen for valid FKs, but cheap).
DO $$
DECLARE
  fk_rec record;
BEGIN
  FOR fk_rec IN
    SELECT DISTINCT con.conname
    FROM pg_constraint con
    JOIN pg_class rel ON rel.oid = con.conrelid
    JOIN pg_namespace nsp ON nsp.oid = rel.relnamespace
    LEFT JOIN pg_attribute att
      ON att.attrelid = con.conrelid
     AND att.attnum = ANY(con.conkey)
    WHERE nsp.nspname = 'public'
      AND rel.relname = 'tenant_entity_relations'
      AND con.contype = 'f'
      AND con.confdeltype <> 'c'  -- 'c' = CASCADE; anything else is wrong
      AND (
        att.attname IN ('source_field_id', 'target_field_id')         -- (a) column-based
        OR
        con.conname IN (                                              -- (b) name-based fallback
          'tenant_entity_relations_source_field_id_fkey',
          'tenant_entity_relations_target_field_id_fkey'
        )
      )
  LOOP
    EXECUTE format(
      'ALTER TABLE public.tenant_entity_relations DROP CONSTRAINT %I',
      fk_rec.conname
    );
    RAISE NOTICE 'Dropped stale FK % (non-CASCADE delete action on source/target_field_id)', fk_rec.conname;
  END LOOP;
END $$;

-- 2b. Create FKs with CASCADE if not already present (idempotent).
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'tenant_entity_relations_source_field_id_fkey'
  ) THEN
    ALTER TABLE public.tenant_entity_relations
      ADD CONSTRAINT tenant_entity_relations_source_field_id_fkey
      FOREIGN KEY (source_field_id)
      REFERENCES public.tenant_field_definitions(id)
      ON DELETE CASCADE;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'tenant_entity_relations_target_field_id_fkey'
  ) THEN
    ALTER TABLE public.tenant_entity_relations
      ADD CONSTRAINT tenant_entity_relations_target_field_id_fkey
      FOREIGN KEY (target_field_id)
      REFERENCES public.tenant_field_definitions(id)
      ON DELETE CASCADE;
  END IF;
END $$;

-- 3. Integrity guard — both field IDs present or both NULL (never mismatched).
--    Safe with the CASCADE FKs in §2 because deleting a field removes the
--    whole row, so the CHECK is never violated during a cascading delete.
ALTER TABLE public.tenant_entity_relations
  DROP CONSTRAINT IF EXISTS chk_field_level_pair;
ALTER TABLE public.tenant_entity_relations
  ADD CONSTRAINT chk_field_level_pair
  CHECK (
    (source_field_id IS NULL AND target_field_id IS NULL)
    OR
    (source_field_id IS NOT NULL AND target_field_id IS NOT NULL)
  );

-- 4. Performance indexes for the typical Schema Builder queries
CREATE INDEX IF NOT EXISTS idx_ter_source_field
  ON public.tenant_entity_relations (source_field_id)
  WHERE source_field_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_ter_target_field
  ON public.tenant_entity_relations (target_field_id)
  WHERE target_field_id IS NOT NULL;

-- 5. Realtime publication — idempotent add
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime'
      AND schemaname = 'public'
      AND tablename = 'tenant_entity_relations'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.tenant_entity_relations;
  END IF;
END $$;

