-- =============================================================================
-- browse.*  — every tenant-scoped table, with the TENANT NAME instead of a UUID
-- =============================================================================
--
-- THE PROBLEM, in the operator's words (2026-08-17):
--
--   "in supabase, i can only see tenant ID on all tables but i can't see the
--    tenant name."
--
-- 286 tables in `public` carry a `tenant_id`. Seven tenants exist. Browsing any
-- table in Supabase Studio shows an opaque UUID, so answering "whose row is
-- this?" means copying a UUID and looking it up by hand, every time.
--
-- A foreign key does not solve it. 254 of those 286 already HAVE an FK to
-- `tenants.id` — Studio still renders the UUID. (The 32 that lack one are a
-- separate, real integrity gap, tracked separately; this migration does not add
-- them, because adding 32 FKs is a data-integrity change that deserves its own
-- review rather than riding along with a convenience feature.)
--
-- WHAT THIS SHIPS
--
-- A `browse` schema holding one view per tenant-scoped table:
--
--     browse.<table>  =  SELECT t.name AS tenant, x.*
--                        FROM public.<table> x
--                        LEFT JOIN public.tenants t ON t.id = x.tenant_id
--
-- `tenant` comes FIRST so it is the leftmost column in Studio. LEFT JOIN, not
-- inner: a row whose tenant_id is NULL (global/reference data) must still be
-- visible, and an inner join would silently delete exactly the rows most likely
-- to be interesting. That is not hypothetical — crm7's Company picker hid 91% of
-- clients that way, found the same day.
--
-- ─────────────────────────────────────────────────────────────────────────────
-- SECURITY: `security_invoker = true` IS THE WHOLE MIGRATION. READ THIS BEFORE
-- EDITING ANYTHING BELOW.
-- ─────────────────────────────────────────────────────────────────────────────
--
-- In PostgreSQL a view executes as its OWNER by default. A view owned by
-- `postgres` over an RLS-protected table therefore BYPASSES that table's row
-- level security — the caller sees every tenant's rows. Creating 286 such views
-- would be the single largest cross-tenant hole this estate has ever had, and it
-- would look like a convenience feature.
--
-- `WITH (security_invoker = true)` makes each view execute as the CALLER, so the
-- base table's RLS policies apply exactly as they do today. This schema grants
-- NO additional visibility to anyone: it is a display convenience over rows the
-- caller could already read.
--
-- Requires PostgreSQL 15+. Production is 17.6 (verified 2026-08-17), and the DO
-- block below REFUSES to run below 15 rather than silently creating definer
-- views. A partial failure here is safe; a silent success would not be.
--
-- anon is revoked by name AND via PUBLIC. Neither covers the other: a
-- postgres-created object carries a built-in grant to PUBLIC that
-- ALTER DEFAULT PRIVILEGES does not remove, while a supabase_admin-created one
-- gets a direct anon grant instead. Both routes are closed, then asserted back.
-- =============================================================================

-- Refuse outright on a version that cannot enforce invoker semantics.
DO $guard$
BEGIN
  IF current_setting('server_version_num')::int < 150000 THEN
    RAISE EXCEPTION
      'browse.* requires PostgreSQL 15+ for security_invoker; this server is %. '
      'Refusing to create views that would bypass RLS on 286 tenant-scoped tables.',
      current_setting('server_version');
  END IF;
END
$guard$;

CREATE SCHEMA IF NOT EXISTS browse;

COMMENT ON SCHEMA browse IS
  'Read-only display views: every tenant-scoped public table with the tenant NAME '
  'as the leading column instead of a bare UUID. Every view is security_invoker, '
  'so RLS on the base table applies unchanged — this schema grants no additional '
  'visibility, it only makes existing visibility legible. Generated by '
  '20260822000000; re-run that migration after adding a tenant-scoped table.';

DO $build$
DECLARE
  r          record;
  made               int := 0;
  skipped            int := 0;
  skipped_type       int := 0;
  skipped_collision  int := 0;
BEGIN
  FOR r IN
    SELECT c.relname AS tbl, format_type(a.atttypid, a.atttypmod) AS tid_type
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    JOIN pg_attribute a ON a.attrelid = c.oid
    WHERE n.nspname = 'public'
      AND c.relkind = 'r'
      AND a.attname = 'tenant_id'
      AND a.attnum > 0
      AND NOT a.attisdropped
      AND c.relname <> 'tenants'
    ORDER BY c.relname
  LOOP
    -- A tenant_id that is not a uuid cannot join to tenants.id, and cannot carry
    -- an FK to it either — which is part of why some tables have no key at all.
    -- Skipped LOUDLY rather than cast: a silent `::uuid` would throw at runtime on
    -- the first non-uuid string, and papering over it here would hide the real
    -- defect, which is the column type. Measured 2026-08-17: 291 tables are uuid
    -- and exactly one is not (page_drafts), so this is a named data defect rather
    -- than a shape this migration should learn to tolerate.
    IF r.tid_type <> 'uuid' THEN
      RAISE WARNING
        'browse: SKIPPING public.% — tenant_id is %, not uuid. It cannot join to '
        'tenants.id nor carry a foreign key to it. Fix the column type.',
        r.tbl, r.tid_type;
      skipped := skipped + 1; skipped_type := skipped_type + 1;
      CONTINUE;
    END IF;

    -- A base table with a column already called `tenant` would collide with the
    -- one this view prepends. Skip it loudly rather than shadowing a real column.
    IF EXISTS (
      SELECT 1 FROM pg_attribute a2
      JOIN pg_class c2 ON c2.oid = a2.attrelid
      JOIN pg_namespace n2 ON n2.oid = c2.relnamespace
      WHERE n2.nspname = 'public' AND c2.relname = r.tbl
        AND a2.attname = 'tenant' AND a2.attnum > 0 AND NOT a2.attisdropped
    ) THEN
      RAISE NOTICE 'browse: skipping public.% — it already has a column named "tenant"', r.tbl;
      skipped := skipped + 1; skipped_collision := skipped_collision + 1;
      CONTINUE;
    END IF;

    EXECUTE format(
      'CREATE OR REPLACE VIEW browse.%I WITH (security_invoker = true) AS '
      'SELECT t.name AS tenant, x.* FROM public.%I x '
      'LEFT JOIN public.tenants t ON t.id = x.tenant_id',
      r.tbl, r.tbl);

    EXECUTE format('REVOKE ALL ON browse.%I FROM PUBLIC', r.tbl);
    EXECUTE format('REVOKE ALL ON browse.%I FROM anon', r.tbl);
    EXECUTE format('GRANT SELECT ON browse.%I TO authenticated, service_role', r.tbl);

    made := made + 1;
  END LOOP;

  -- Scanning nothing must not read as success.
  IF made = 0 THEN
    RAISE EXCEPTION
      'browse: created 0 views. Either no public table carries tenant_id (false — '
      'there were 286 on 2026-08-17) or this block cannot see pg_catalog. Refusing '
      'to report a successful build over an empty schema.';
  END IF;

  -- Two different reasons to skip, reported as one number would be a small lie of
  -- exactly the kind this estate keeps paying for. Name them separately.
  RAISE NOTICE
    'browse: % view(s) created; % skipped (% for a non-uuid tenant_id, % for an '
    'existing "tenant" column)', made, skipped, skipped_type, skipped_collision;
END
$build$;

REVOKE ALL ON SCHEMA browse FROM PUBLIC;
REVOKE ALL ON SCHEMA browse FROM anon;
GRANT USAGE ON SCHEMA browse TO authenticated, service_role;

-- Anything added to browse later inherits the same posture rather than the
-- permissive default.
ALTER DEFAULT PRIVILEGES IN SCHEMA browse REVOKE ALL ON TABLES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES IN SCHEMA browse REVOKE ALL ON TABLES FROM anon;
ALTER DEFAULT PRIVILEGES IN SCHEMA browse GRANT SELECT ON TABLES TO authenticated, service_role;

-- =============================================================================
-- ASSERT THE POSTURE BACK. A migration that issues a REVOKE and never re-reads
-- the catalog has proved nothing — this estate has shipped that mistake before.
-- =============================================================================
DO $assert$
DECLARE
  n_views     int;
  n_definer   int;
  anon_usage  boolean;
  anon_reads  int;
BEGIN
  SELECT count(*) INTO n_views
  FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
  WHERE n.nspname = 'browse' AND c.relkind = 'v';

  IF n_views = 0 THEN
    RAISE EXCEPTION 'browse: 0 views exist after the build block. Aborting.';
  END IF;

  -- THE ONE THAT MATTERS. A definer view here is a cross-tenant read of the
  -- whole estate.
  SELECT count(*) INTO n_definer
  FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
  WHERE n.nspname = 'browse' AND c.relkind = 'v'
    AND NOT COALESCE((SELECT option_value::boolean
                        FROM pg_options_to_table(c.reloptions)
                       WHERE option_name = 'security_invoker'), false);

  IF n_definer > 0 THEN
    RAISE EXCEPTION
      'browse: % view(s) are SECURITY DEFINER and would bypass RLS on their base '
      'tables, exposing every tenant. Refusing to leave them in place.', n_definer;
  END IF;

  SELECT has_schema_privilege('anon', 'browse', 'USAGE') INTO anon_usage;
  IF anon_usage THEN
    RAISE EXCEPTION 'browse: anon still holds USAGE on the schema.';
  END IF;

  SELECT count(*) INTO anon_reads
  FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
  WHERE n.nspname = 'browse' AND c.relkind = 'v'
    AND has_table_privilege('anon', c.oid, 'SELECT');

  IF anon_reads > 0 THEN
    RAISE EXCEPTION 'browse: anon can still SELECT from % view(s).', anon_reads;
  END IF;

  RAISE NOTICE
    'browse: % view(s), all security_invoker, anon has neither USAGE nor SELECT.',
    n_views;
END
$assert$;
