-- =====================================================
-- Migration: Jodie GitHub App webhook queue + installation token cache
-- =====================================================

CREATE TABLE IF NOT EXISTS public.jodie_webhook_queue (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  delivery_guid TEXT NOT NULL UNIQUE,
  event_name TEXT NOT NULL,
  action TEXT,
  payload JSONB NOT NULL,
  status TEXT NOT NULL DEFAULT 'queued' CHECK (status IN ('queued', 'processing', 'processed', 'failed')),
  attempts INTEGER NOT NULL DEFAULT 0 CHECK (attempts >= 0),
  received_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  processed_at TIMESTAMPTZ,
  error_message TEXT
);

CREATE INDEX IF NOT EXISTS idx_jodie_webhook_queue_status_received_at
  ON public.jodie_webhook_queue (status, received_at);

CREATE TABLE IF NOT EXISTS public.jodie_app_installations (
  installation_id BIGINT PRIMARY KEY,
  account_login TEXT,
  account_type TEXT,
  installation_target_type TEXT,
  repository_selection TEXT,
  permissions JSONB NOT NULL DEFAULT '{}'::JSONB,
  access_token TEXT NOT NULL,
  token_expires_at TIMESTAMPTZ NOT NULL,
  refreshed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE OR REPLACE FUNCTION public.set_jodie_app_installations_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS jodie_app_installations_updated_at ON public.jodie_app_installations;
CREATE TRIGGER jodie_app_installations_updated_at
  BEFORE UPDATE ON public.jodie_app_installations
  FOR EACH ROW
  EXECUTE FUNCTION public.set_jodie_app_installations_updated_at();

CREATE OR REPLACE FUNCTION public.enqueue_jodie_webhook(
  p_delivery_guid TEXT,
  p_event_name TEXT,
  p_action TEXT,
  p_payload JSONB
)
RETURNS TABLE(inserted BOOLEAN)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.jodie_webhook_queue (
    delivery_guid,
    event_name,
    action,
    payload
  )
  VALUES (
    p_delivery_guid,
    p_event_name,
    p_action,
    p_payload
  )
  ON CONFLICT (delivery_guid) DO NOTHING;

  RETURN QUERY SELECT FOUND;
END;
$$;

ALTER TABLE public.jodie_webhook_queue ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.jodie_app_installations ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "jodie_webhook_queue_admin_select" ON public.jodie_webhook_queue;
CREATE POLICY "jodie_webhook_queue_admin_select"
  ON public.jodie_webhook_queue
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM public.profiles
      WHERE id = auth.uid()
        AND platform_role IN ('developer', 'platform_admin')
    )
  );

DROP POLICY IF EXISTS "jodie_webhook_queue_admin_update" ON public.jodie_webhook_queue;
CREATE POLICY "jodie_webhook_queue_admin_update"
  ON public.jodie_webhook_queue
  FOR UPDATE
  TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM public.profiles
      WHERE id = auth.uid()
        AND platform_role IN ('developer', 'platform_admin')
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1
      FROM public.profiles
      WHERE id = auth.uid()
        AND platform_role IN ('developer', 'platform_admin')
    )
  );

DROP POLICY IF EXISTS "jodie_webhook_queue_admin_delete" ON public.jodie_webhook_queue;
CREATE POLICY "jodie_webhook_queue_admin_delete"
  ON public.jodie_webhook_queue
  FOR DELETE
  TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM public.profiles
      WHERE id = auth.uid()
        AND platform_role IN ('developer', 'platform_admin')
    )
  );

DROP POLICY IF EXISTS "jodie_app_installations_admin_select" ON public.jodie_app_installations;
CREATE POLICY "jodie_app_installations_admin_select"
  ON public.jodie_app_installations
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM public.profiles
      WHERE id = auth.uid()
        AND platform_role IN ('developer', 'platform_admin')
    )
  );

DROP POLICY IF EXISTS "jodie_app_installations_admin_insert" ON public.jodie_app_installations;
CREATE POLICY "jodie_app_installations_admin_insert"
  ON public.jodie_app_installations
  FOR INSERT
  TO authenticated
  WITH CHECK (
    EXISTS (
      SELECT 1
      FROM public.profiles
      WHERE id = auth.uid()
        AND platform_role IN ('developer', 'platform_admin')
    )
  );

DROP POLICY IF EXISTS "jodie_app_installations_admin_update" ON public.jodie_app_installations;
CREATE POLICY "jodie_app_installations_admin_update"
  ON public.jodie_app_installations
  FOR UPDATE
  TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM public.profiles
      WHERE id = auth.uid()
        AND platform_role IN ('developer', 'platform_admin')
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1
      FROM public.profiles
      WHERE id = auth.uid()
        AND platform_role IN ('developer', 'platform_admin')
    )
  );

DROP POLICY IF EXISTS "jodie_app_installations_admin_delete" ON public.jodie_app_installations;
CREATE POLICY "jodie_app_installations_admin_delete"
  ON public.jodie_app_installations
  FOR DELETE
  TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM public.profiles
      WHERE id = auth.uid()
        AND platform_role IN ('developer', 'platform_admin')
    )
  );

GRANT EXECUTE ON FUNCTION public.enqueue_jodie_webhook(TEXT, TEXT, TEXT, JSONB) TO authenticated;
