import type {
  Apprentice,
  ApprenticeDocument,
  DashboardMetric,
  Timesheet,
  WHSIncident,
} from '@/types';

// ─── Dashboard Metrics ──────────────────────────────────────────────────────

export const MOCK_METRICS: DashboardMetric[] = [
  { label: 'Active Apprentices', value: 47, trend: 'up', trendValue: '+3' },
  { label: 'Pending Timesheets', value: 12, trend: 'down', trendValue: '-2' },
  { label: 'Upcoming Reviews', value: 8, trend: 'neutral', trendValue: '' },
  { label: 'WHS Incidents', value: 2, trend: 'down', trendValue: '-1' },
];

// ─── Apprentices ─────────────────────────────────────────────────────────────

export const MOCK_APPRENTICES: Apprentice[] = [
  {
    id: '1',
    firstName: 'Jake',
    lastName: 'Morrison',
    email: 'jake.morrison@email.com',
    phone: '0412 345 678',
    avatarUrl: null,
    status: 'active',
    qualification: 'Certificate III in Electrotechnology',
    startDate: '2025-02-15',
    expectedEndDate: '2028-02-15',
    hostEmployer: {
      id: 'he-1',
      name: 'Spark Electrical Services',
      contactName: 'David Chen',
      contactPhone: '0498 765 432',
      contactEmail: 'david@sparkelectrical.com.au',
      address: '42 Industrial Dr, Smithfield QLD 4878',
    },
    emergencyContact: {
      name: 'Sarah Morrison',
      relationship: 'Mother',
      phone: '0421 987 654',
    },
  },
  {
    id: '2',
    firstName: 'Mia',
    lastName: 'Nguyen',
    email: 'mia.nguyen@email.com',
    phone: '0423 456 789',
    avatarUrl: null,
    status: 'active',
    qualification: 'Certificate III in Carpentry',
    startDate: '2025-06-01',
    expectedEndDate: '2028-06-01',
    hostEmployer: {
      id: 'he-2',
      name: 'North Coast Builders',
      contactName: 'Tim Walsh',
      contactPhone: '0487 654 321',
      contactEmail: 'tim@northcoastbuilders.com.au',
      address: '15 Harbour Rd, Port Douglas QLD 4877',
    },
    emergencyContact: {
      name: 'Linh Nguyen',
      relationship: 'Father',
      phone: '0432 876 543',
    },
  },
  {
    id: '3',
    firstName: 'Liam',
    lastName: 'O\'Brien',
    email: 'liam.obrien@email.com',
    phone: '0434 567 890',
    avatarUrl: null,
    status: 'active',
    qualification: 'Certificate III in Plumbing',
    startDate: '2025-03-10',
    expectedEndDate: '2028-03-10',
    hostEmployer: {
      id: 'he-3',
      name: 'AquaFlow Plumbing',
      contactName: 'Karen Miller',
      contactPhone: '0476 543 210',
      contactEmail: 'karen@aquaflow.com.au',
      address: '88 Trade Circuit, Edmonton QLD 4869',
    },
    emergencyContact: {
      name: 'Patrick O\'Brien',
      relationship: 'Father',
      phone: '0443 765 432',
    },
  },
  {
    id: '4',
    firstName: 'Sophie',
    lastName: 'Taylor',
    email: 'sophie.taylor@email.com',
    phone: '0445 678 901',
    avatarUrl: null,
    status: 'suspended',
    qualification: 'Certificate III in Air Conditioning',
    startDate: '2025-01-20',
    expectedEndDate: '2028-01-20',
    hostEmployer: {
      id: 'he-4',
      name: 'CoolTech HVAC',
      contactName: 'Mike Thompson',
      contactPhone: '0465 432 109',
      contactEmail: 'mike@cooltech.com.au',
      address: '23 Workshop Lane, Bungalow QLD 4870',
    },
    emergencyContact: {
      name: 'Jenny Taylor',
      relationship: 'Mother',
      phone: '0454 654 321',
    },
  },
  {
    id: '5',
    firstName: 'Ben',
    lastName: 'Williams',
    email: 'ben.williams@email.com',
    phone: '0456 789 012',
    avatarUrl: null,
    status: 'completed',
    qualification: 'Certificate III in Engineering - Mechanical Trade',
    startDate: '2023-01-15',
    expectedEndDate: '2026-01-15',
    hostEmployer: {
      id: 'he-5',
      name: 'Precision Engineering FNQ',
      contactName: 'Angela Ross',
      contactPhone: '0454 321 098',
      contactEmail: 'angela@precisioneng.com.au',
      address: '7 Factory St, Portsmith QLD 4870',
    },
    emergencyContact: {
      name: 'Dave Williams',
      relationship: 'Father',
      phone: '0465 543 210',
    },
  },
];

// ─── Timesheets ──────────────────────────────────────────────────────────────

export const MOCK_TIMESHEETS: Timesheet[] = [
  {
    id: 'ts-1',
    apprenticeId: '1',
    apprenticeName: 'Jake Morrison',
    weekStarting: '2026-02-23',
    weekEnding: '2026-02-27',
    totalHours: 38,
    ordinaryHours: 38,
    overtimeHours: 0,
    status: 'pending',
    submittedAt: '2026-02-27T17:00:00Z',
    approvedBy: null,
    approvedAt: null,
    notes: null,
  },
  {
    id: 'ts-2',
    apprenticeId: '2',
    apprenticeName: 'Mia Nguyen',
    weekStarting: '2026-02-23',
    weekEnding: '2026-02-27',
    totalHours: 42,
    ordinaryHours: 38,
    overtimeHours: 4,
    status: 'pending',
    submittedAt: '2026-02-27T16:30:00Z',
    approvedBy: null,
    approvedAt: null,
    notes: 'Overtime approved by supervisor for urgent project',
  },
  {
    id: 'ts-3',
    apprenticeId: '3',
    apprenticeName: 'Liam O\'Brien',
    weekStarting: '2026-02-23',
    weekEnding: '2026-02-27',
    totalHours: 38,
    ordinaryHours: 38,
    overtimeHours: 0,
    status: 'approved',
    submittedAt: '2026-02-27T15:00:00Z',
    approvedBy: 'Field Officer',
    approvedAt: '2026-02-28T09:00:00Z',
    notes: null,
  },
  {
    id: 'ts-4',
    apprenticeId: '1',
    apprenticeName: 'Jake Morrison',
    weekStarting: '2026-02-16',
    weekEnding: '2026-02-20',
    totalHours: 36,
    ordinaryHours: 36,
    overtimeHours: 0,
    status: 'approved',
    submittedAt: '2026-02-20T17:00:00Z',
    approvedBy: 'Field Officer',
    approvedAt: '2026-02-21T10:00:00Z',
    notes: 'Short week — RDO Monday',
  },
  {
    id: 'ts-5',
    apprenticeId: '2',
    apprenticeName: 'Mia Nguyen',
    weekStarting: '2026-02-16',
    weekEnding: '2026-02-20',
    totalHours: 30,
    ordinaryHours: 30,
    overtimeHours: 0,
    status: 'rejected',
    submittedAt: '2026-02-20T16:45:00Z',
    approvedBy: null,
    approvedAt: null,
    notes: 'Missing host employer signature',
  },
];

// ─── WHS Incidents ───────────────────────────────────────────────────────────

export const MOCK_INCIDENTS: WHSIncident[] = [
  {
    id: 'whs-1',
    type: 'near_miss',
    severity: 'medium',
    status: 'investigating',
    title: 'Unsecured ladder on scaffolding',
    description:
      'Apprentice noticed an unsecured extension ladder leaning against scaffolding at the rear of the site. No injury occurred but it could have fallen onto the walkway below.',
    location: '42 Industrial Dr, Smithfield',
    reportedBy: 'Jake Morrison',
    reportedAt: '2026-02-26T10:30:00Z',
    apprenticeId: '1',
    apprenticeName: 'Jake Morrison',
    resolvedAt: null,
    photos: [],
  },
  {
    id: 'whs-2',
    type: 'injury',
    severity: 'low',
    status: 'resolved',
    title: 'Minor cut from sheet metal',
    description:
      'Apprentice sustained a small cut on the left hand while handling sheet metal offcuts. First aid administered on site. No further treatment required.',
    location: '7 Factory St, Portsmith',
    reportedBy: 'Ben Williams',
    reportedAt: '2026-02-24T14:15:00Z',
    apprenticeId: '5',
    apprenticeName: 'Ben Williams',
    resolvedAt: '2026-02-24T15:00:00Z',
    photos: [],
  },
  {
    id: 'whs-3',
    type: 'hazard',
    severity: 'high',
    status: 'reported',
    title: 'Exposed wiring in ceiling cavity',
    description:
      'During routine ceiling inspection, exposed live wiring was discovered that was not shown on the site electrical plan. Area cordoned off pending licensed electrician review.',
    location: '15 Harbour Rd, Port Douglas',
    reportedBy: 'Mia Nguyen',
    reportedAt: '2026-02-27T09:45:00Z',
    apprenticeId: '2',
    apprenticeName: 'Mia Nguyen',
    resolvedAt: null,
    photos: [],
  },
];

// ─── Documents ───────────────────────────────────────────────────────────────

export const MOCK_DOCUMENTS: Record<string, ApprenticeDocument[]> = {
  '1': [
    {
      id: 'doc-1',
      name: 'White Card',
      type: 'license',
      expiryDate: null,
      status: 'current',
      fileUrl: '',
      uploadedAt: '2025-02-15T00:00:00Z',
    },
    {
      id: 'doc-2',
      name: 'First Aid Certificate',
      type: 'certificate',
      expiryDate: '2027-03-01',
      status: 'current',
      fileUrl: '',
      uploadedAt: '2025-03-01T00:00:00Z',
    },
    {
      id: 'doc-3',
      name: 'Training Plan',
      type: 'document',
      expiryDate: null,
      status: 'current',
      fileUrl: '',
      uploadedAt: '2025-02-20T00:00:00Z',
    },
  ],
  '2': [
    {
      id: 'doc-4',
      name: 'White Card',
      type: 'license',
      expiryDate: null,
      status: 'current',
      fileUrl: '',
      uploadedAt: '2025-06-01T00:00:00Z',
    },
    {
      id: 'doc-5',
      name: 'Working at Heights',
      type: 'certificate',
      expiryDate: '2026-04-15',
      status: 'expiring_soon',
      fileUrl: '',
      uploadedAt: '2025-06-10T00:00:00Z',
    },
  ],
};
